### ISSUE TITLE
Importer Button Doesn't Appear Under Compendium

### ISSUE THREAD

**Issue by emorgan33** [farling42/fvtt-import-realmworks#38]
I'm having the issue of the Realm Works importer button not showing in the compendium. I have the module activated and updated. I'm using the PF2e system version 2.11.1.7257 and Foundry VTT 0.8.9.

This would be my first time using this module.

Thank you.

**Comment by farling42** [comment]
Hello, Please could you open your browser console (press F12 on PC), and look for any error that might indicate why the module is failing to start properly. The button appears near the TOP of the compendium now. I might have out-of-date documentation. Regards,MartinOn 20 Aug 2021 17:50, emorgan33 ***@***.***> wrote:
I'm having the issue of the Realm Works importer button not showing in the compendium. I have the module activated and updated. I'm using the PF2e system version 2.11.1.7257 and Foundry VTT 0.8.9.
This would be my first time using this module.
Thank you.

**Comment by emorgan33** [comment]
The only errors I have are these:
Name: "
     aria-labelledby: Not specified
     aria-label: Not specified
     title: Not specified
  Role: generic

I'm using the Foundry VTT in the standalone application.

Thanks.

**Comment by farling42** [comment]
With the module enabled, what do you see at the top of the Compendium Packs panel?

On my test world, I see:
Create Compendium
Seacrch Compendia
Realm Works Import

When you first start the world, in the F12 console, at the very top of the log, are these the first lines that appear?

''module.mjs:75 Foundry VTT | Foundry Commons Framework Loaded
foundry.js:53598 _______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  
===============================================================
foundry.js:53608 Foundry VTT | Reestablishing existing session''

**Comment by emorgan33** [comment]
With the module enabled, what do you see at the top of the Compendium Packs panel?

1. Create Compendium
2. Search Compendia
and at the bottom: Compendium Browser

When you first start the world, in the F12 console, at the very top of the log, are these the first lines that appear?

Here's what appears in mine:

Foundry VTT | Foundry Commons Framework Loaded   module.mjs:75
Failed to load resource: the server responded with a status of 404 (Not Found)  config.js:1
foundry.js:53598 _______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  
===============================================================

**Comment by farling42** [comment]
My module tries to load config.js for the DND5E game system.
Because you don't have this installed you are getting this error.

It is a bug on my side, but if you were to install the DND5E game system then the plugin will work until I get a fix in on my side.

**Comment by emorgan33** [comment]
Excellent! I installed the dnd5e and the import button appears now. 

Thanks for your help and for writing this importer!

**Comment by farling42** [comment]
As of 0.4.1 you should no longer need to have the dnd5e game system installed :)
