### ISSUE TITLE
Image Conversion to WEBP

### ISSUE THREAD

**Issue by MerionLial** [farling42/fvtt-import-realmworks#58]
When uploading images directly to Foundry, I try to convert everything to webp. It's just so much smaller and helps players on low-end machines and with mediocre internet connection.

As most of my content enters Foundry through the Realm Works Importer and Realm Works can only work with jpg and png, most of the images in my Foundry are unnecessarily large.

So the Feature Request is: Please add an option to convert images from jpg or png to webp during the import process.

**Comment by farling42** [comment]
See https://stackoverflow.com/questions/62209609/how-to-convert-any-image-to-webp/62256291#62256291
for a possible use of canvas for image format conversion

**Comment by farling42** [comment]
Version 1.20 provides an option to convert all images to the WEBP format.
