### ISSUE TITLE
Creating 9938 empty items and journal entries

### ISSUE THREAD

**Issue by Trellinane** [farling42/fvtt-import-realmworks#63]
I am attempting to import a Realm Works campaign and when I follow the instructions it indicates it is reading the export file and then indicates Creating 9938 empty items and journal entries.  It does create the folders as named by me in the import screen under scenes, actors, playlists and journals.  There is nothing in the folders except under the journal tab.  In the folder of the journal tab all of my topics are listed but there is no data in any of them.

I did open the export file from RealmWorks and my campaign data is indeed contained in the export file.  The Export file is about 580MB in size.

This is on Foundry version 9.269 and with RealmWorks Importer Ver 1.23.

As an edit, I tried importing a Hero Lab sample file for 5th Edition D&D and it did seem to function just fine.  I don't know if the issue lies with my Realmworks export being so large or not.  I was also able to enter smaller single topic entries from RealmWorks of less than 1MB.

**Comment by farling42** [comment]
I don't think the size is an issue. I have tested with 430 MB (which is my biggest realm).

It is worth noting that Firefox is not a good browser to use for doing the import, as it doesn't manage it's memory very well for this size of realm. Chrome handles things a lot better.

Can you open the browser console (F12) and look in the Console tab of that extra panel to see if any errors are reported during import.

**Comment by Trellinane** [comment]
It appears I may be been utilizing an incorrect export tag which of course would have returned zero items since I had not tagged anything with the export tag being used in the actual export tag tab.  I have had several successful imports of parts of my realm since.  I will attempt a full import shortly and let you know about any issues.  Sorry for the mix up.

As an aside, nearly everything being imported is coming in as a journal article including things like weapons and equipment.  Is there something I am doing incorrectly in Realm Works that is not allowing the Realm Works entry to be identified as an item in Foundry via the import module.

**Comment by farling42** [comment]
The detection of Items only works for the PF1 game system, and it maps the Realm Works category onto the following Foundry Item types:

Magic Item  => equipment
Mundane Weapon   => equipment
Mundane Item   => equipment
Mundane Armor/Shield   => equipment
Named Object   => equipment
Named Equipment   => equipment
Feat   => feat
Archetype/Domain/Etc.  => feat
Trait/Drawback  => feat
Skill  => feat
Race   => race
Class   => class
Spell   = >spell


The name of the Realm Works category must match (or start with) one of the above strings.

**Comment by Trellinane** [comment]
Thank you so much for your responses and I apologize for opening what appears to be an issue in my Realm Works classifications.  Incredible mod and I expect it will save me a great deal of time.  Is there a better way to communicate before I open issues in the future or should I continue with this venue and potentially expose my ignorance again.  Lol.

**Comment by farling42** [comment]
This is a perfectly fine way to discuss issues with me.
It is far easier to follow a thread of conversation in a single issue, rather than trying to track a set of messages in a discord channel. :-)
