### ISSUE TITLE
Walls and Door

### ISSUE THREAD

**Issue by taspoff** [farling42/fvtt-import-realmworks#79]
Hi!

RealmWorks Smart Maps does not have Walls and Doors, that have to be drawn in Foundry. But we have possibility to stock JSON files as "foreign object" in RW.

Beside, we can export Scenes Data as JSON File in Foundry, with Walls and Doors, and other informations.

Would it be possible, while importing a JSON foreign object in Foundry, to check if a scene already exist with the same name, and if yes, to automatically use the json as "import scene" in foundry?

(Your module Rocks! It's way easier to manage campaign and NPC with it!)

**Comment by farling42** [comment]
Oops, don't worry about the import/export, I just found it - the scene has to already exist before you can access Import from the popup menu.

**Comment by farling42** [comment]
A general solution is support any JSON files stored in the RW realm whose filename is of the format `fvtt-<objecttype>-<name>.json` and import the file after all normal RW importing has been performed.

The JSON has the correct name inside it, so this can be used to match it up to the correct entry in Foundry.

**Comment by farling42** [comment]
Implemented in release 2.7 as a general mechanism for storing any Foundry "Export Data" file.
