### ISSUE TITLE
Create link in RW pointing to non-RW Foundry documents

### ISSUE THREAD

**Issue by MerionLial** [farling42/fvtt-import-realmworks#80]
This one is a bit tough to explain...

The game system, in my case PF 1e, already comes with some items, journal entries etc. Would it possible to create a link in Realm Works to a topic that does not exist in RW but once imported into Foundry the link will lead to the correct thing?

Maybe better with an example:
In a scene in Realm Works I write in the 'Rewards' section, that the players can find a Belt of Incredible Dexterity +2. In my realm, there's no topic or article like this. But in my Foundry world that item exists.
Now, how could I manage it, that after importing that scene into Foundry, the words 'Belt of Incredible Dexterity +2' become a link to the item?
I can't create internal RW links that point nowhere, as far as I know. Maybe the hyperlink could be repurposed somehow? Or I could add a placeholder string that your importer recognized and creates the link. Something like [[foundry_link::Belt of Incredible Dexterity +2]] or any other convention.

**Comment by farling42** [comment]
You could probably achieve this by putting the existing Foundry links into the realm works topic. Using the older type of link you can use the name of the Foundry thing rather than always needing to use the uuid.

So you could put `@Item[Belt of Incredible Dexterity +2]` and if such an item exists, then the link should work automatically.

I don't think that the RW Importer does any stripping out of these links.

**Comment by farling42** [comment]
You can even use the `@UUID[item id]{label}` syntax if you are happy to do the copy-and-paste from Foundry to RW.

**Comment by MerionLial** [comment]
Ah! Didn't think of the most obvious solution!

Going to try this out tomorrow. Thankfully the Quick Insert module let's me grap links like @Compendium[pf1.items.PC3K6eeXRdUwJxLA]{Belt of Incredible Dexterity +2} very easily.

Thanks for the help!

**Comment by farling42** [comment]
Wood for the Trees :-)

Hopefully it works.

**Comment by MerionLial** [comment]
Just wanted to report back that it works :-)
