### ISSUE TITLE
Support custom compendium for imports

### ISSUE THREAD

**Issue by jpreston84** [farling42/fvtt-import-realmworks#82]
Sometimes, when importing, I want to use a modified class feature or item from my own compendium. A good example of this is the Rogue Sneak Attack. The default one in the pf1 system doesn't include any damage roll, so I want to override with my own feature.

The current functionality means that every time my Rogue (and other players) updates his character sheet in Hero Lab and re-imports it, the Sneak Attack is broken again.

Suggested Implementation: Allow compendiums that are part of the current world to be processed first, so that any custom items added to the world will be preferred when matching up entries for the import. This could be enabled/disabled by a configuration checkbox.

Alternate (Less Desirable) Implementation: Only allow imports for a compendium with a specific name.

I think this would be a really small change to the codebase. I appreciate your consideration.

**Comment by farling42** [comment]
Related to #76

**Comment by farling42** [comment]
Version 2.8 now looks in WORLD compendiums for Items before looking in the SYSTEM or MODULE compendiums.
