### ISSUE TITLE
Directory Game Settings from other modules are bugging

### ISSUE THREAD

**Issue by elizeuangelo** [farling42/fvtt-import-realmworks#86]
This line of code in the DirectoryPicker.js file `$(element).prop("readonly", true);` is making all other modules wich use the same dependency to bug out, turning all similar elements from other modules into readonly inputs.

In my testing, foundry doesn't seem to update readonly settings even when their inputs values changes.

**Comment by farling42** [comment]
Can you give an example of another module which is affected by this?
Are some other modules using a class called DirectoryPicker?

**Comment by farling42** [comment]
Could you test version 2.9.4 to see if this fixes the issue you reported.
