### ISSUE TITLE
I Can not select a compendium for importing items orr Journals...

### ISSUE THREAD

**Issue by taspoff** [farling42/fvtt-import-realmworks#89]
Hello 
I can not specify a compendium to import items or journals... the box is empty.
I tried to create a Folder Realm Works, and empty compendium too but it still does'nt work ...
I use Savage World as World Rules.
Any idea?

![image](https://github.com/user-attachments/assets/6171f21c-3abf-4803-b640-0ce86541a373)

**Comment by taspoff** [comment]
I use foundry V12.331

**Comment by farling42** [comment]
This is caused by a regression in the support provided by version 12 of core Foundry for being able to populate the drop-down menu dynamically.
I am exploring alternative solutions that might work.

**Comment by farling42** [comment]
The dropdown menus should be available in version 2.12.1
