### ISSUE TITLE
Map pins not working when journals in compendiums

### ISSUE THREAD

**Issue by SwordofSpirit** [farling42/fvtt-import-realmworks#91]
The map pins that previously had targets no longer have them.

**Comment by farling42** [comment]
The import is creating notes as expected for me (PF1 on Foundry 11 and 12).

Could you provide the version of Foundry you're using, as well as what game system and the version of that system please.

**Comment by farling42** [comment]
Also, are any errors reported in your browser's console? (which can be opened with F12 on Windows O/S)

**Comment by SwordofSpirit** [comment]
Foundry v12.331
D&D 5e v.3.3.1

I'm not seeing any console error either during import or when looking at the scene or pin.

I'm guessing it must have something to do with the journals being in a compendium. I'm trying to manually create links between map pins and journals in compendiums and I can't figure out how to make it happen.

**Comment by farling42** [comment]
Ah, that would be the issue.
It isn't possible to create Map Notes to journal entries which are stored in compendiums.
Only the "id" of the Journal Note is stored in the Map Note (but the full uuid, which would include the name of the compendium).

**Comment by farling42** [comment]
Core Foundry behaviour is that If a journal entry is dragged from a compendium onto the map, then the journal entry is imported into the Journal sidebar.

**Comment by farling42** [comment]
In the short term, I've added a NOTE into the README indicating that scene notes can't link to journal in compendiums. I will add a similar note into the module's settings panel in the next update.

**Comment by SwordofSpirit** [comment]
Glad to know what the problem is, but dang is that Foundry limitation disappoiting! Now I can't really use that wonderful import to compendium feature, because a bunch of my journals and maps are linked into a giant web of content.

**Comment by farling42** [comment]
Yes, it's unfortunate.
At least the Item compendiums might be a useful feature - although perhaps less useful for world-building purposes.

**Comment by farling42** [comment]
I may investigate a solution in the future, so that directly linked journals are kept in the journal sidebar instead of a compendium, but it probably will make the foundry world look untidy.

**Comment by farling42** [comment]
Version 2.12.3 contains a work-around that will work in Foundry V12 upwards.

If journals are stored in a Compendium, then a local JournalEntry will be created for each note in the world which contains an `@Embed` of the actual journal entry stored in the Compendium.

This should still allow the world to remain a small(ish) size when a large number of journals are created in a Compendium.

(A future evolution might store all those local scene notes as pages in a single journal entry, rather than a separate journal entry for each scene note.)
