### ISSUE TITLE
RealmWorks Home Page Not Imported

### ISSUE THREAD

**Issue by Arbitrary1079** [farling42/fvtt-import-realmworks#94]
The home page with the introuction to your world in RealmWorks (the page that loads when you click the home buttin in RealmWorks) is not imported.

**Comment by farling42** [comment]
Unfortunately, the page you reach by clicking on the HOME button in Realm Works is not actually included in the export file created by Realm Works.

I have no idea why LWD decided not to include it - and they are unlikely to add it since they have stopped all development on Realm Works.
