### ISSUE TITLE
Every Actor seems to  be a Joker...

### ISSUE THREAD

**Issue by taspoff** [farling42/fvtt-import-realmworks#96]
Every NPC I import in foundry goes to Wild caracters, even if not tagged like that in portfolios herolab Classic (On Swade rules)...
Any Idea why?

**Comment by farling42** [comment]
That sounds odd. Maybe the Foundry SWADE code has changed where the wildcard flag is stored (since the importer marks all NPCs as NOT wildcards).

I will need to investigate.

**Comment by farling42** [comment]
There was a bug that's always been in the SWADE actor converter that wasn't setting NPCs correctly. This has been fixed in 2.12.5
